### ISSUE TITLE
linux.consul.-.catalog.nodes_passing needs review

### ISSUE THREAD

**Issue by codytipton** [netuitive-community-packages/netuitive-packages-linux-consul#5]
policy is written (wrongly) as though the metric is only ever 1 or 0 (true/false) for "all nodes registered are currently passing".  This metric is actually a gauge of number of nodes currently passing, and policy should be a threshold.

**Comment by Grumblesmith** [comment]
To clarify, the policy conditions are fine as written, I think, because it's alerting you to a lack of healthy nodes. What's needed is for the description and policy title to tell you that's what you're getting: an alert that all nodes were unhealthy.
